// Mirror of pipeline/common.py slugify() — keep the two in sync so slugs
// generated by the importer and by the admin approval flow are consistent.
export function slugify(text: string): string {
  return text
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
